version: '2'

services:
  app:
    image: peerpub:app 
    ports:
      - "8080:8080"
    links:
      - mongodb
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.181.0/24
