---
spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: peerpub
---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: peerpub
