---
spring:
  profiles: default
  messages:
    basename:
      "i18n/messages"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: peerpub
---
spring:
  profiles: docker
  messages:
    basename:
      "i18n/messages"
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: peerpub
